//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CoreCraft.Input
{
    public partial class @PlayerInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""MenuMap"",
            ""id"": ""a4fab851-c41b-4b4a-b235-50a8e9e4e7bd"",
            ""actions"": [
                {
                    ""name"": ""SettingsTabLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4e463ca2-594a-4b3d-9699-99324cdaedd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SettingsTabRight"",
                    ""type"": ""Button"",
                    ""id"": ""b37fb6af-d932-4632-8db9-9d907eba06d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""82ad53d2-1a7b-485e-81d7-daac712438bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bed925f9-de89-4c34-8cb4-a0e86813c74f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SettingsTabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46c80550-071b-4a77-87c6-91c3ac03153a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SettingsTabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af7dc9eb-d205-4083-b55a-f427b25ba4a4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerMap"",
            ""id"": ""29784d00-4126-4c34-8898-25c87258164a"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""65e830db-edee-48dd-9a1f-e831bb3a069d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9b2d588c-760c-4312-bae8-8ba13bb50ec5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""c2a67070-f077-4dcd-9560-b38200ca98ed"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""4522a9fb-eebb-47e0-bca1-a8b7a418e4d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""8f10f414-b504-4361-8991-ac4e503982b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f6f86b65-7217-4f6c-9a0c-040e8972cd36"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c2d04bfc-5606-4e8b-b379-8278bb95cd66"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a156473b-8e49-440e-b6ad-940f903394ea"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9047d9b1-6efd-431a-9dff-c7b8fcad307e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f01bc1ea-4dc7-4161-a309-6ba45b0d3e70"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e38a6a16-2afc-41d2-a06c-6ef8ebc84d72"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1e7462ae-81ce-4cdd-a3b4-de5a92996cd5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""beb80a59-79ea-43c2-8c4b-5dd7fa9239f9"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56f4b34c-0d48-4e43-94a6-034033a59724"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // MenuMap
            m_MenuMap = asset.FindActionMap("MenuMap", throwIfNotFound: true);
            m_MenuMap_SettingsTabLeft = m_MenuMap.FindAction("SettingsTabLeft", throwIfNotFound: true);
            m_MenuMap_SettingsTabRight = m_MenuMap.FindAction("SettingsTabRight", throwIfNotFound: true);
            m_MenuMap_Escape = m_MenuMap.FindAction("Escape", throwIfNotFound: true);
            // PlayerMap
            m_PlayerMap = asset.FindActionMap("PlayerMap", throwIfNotFound: true);
            m_PlayerMap_Interact = m_PlayerMap.FindAction("Interact", throwIfNotFound: true);
            m_PlayerMap_Move = m_PlayerMap.FindAction("Move", throwIfNotFound: true);
            m_PlayerMap_Look = m_PlayerMap.FindAction("Look", throwIfNotFound: true);
            m_PlayerMap_Run = m_PlayerMap.FindAction("Run", throwIfNotFound: true);
            m_PlayerMap_Crouch = m_PlayerMap.FindAction("Crouch", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // MenuMap
        private readonly InputActionMap m_MenuMap;
        private IMenuMapActions m_MenuMapActionsCallbackInterface;
        private readonly InputAction m_MenuMap_SettingsTabLeft;
        private readonly InputAction m_MenuMap_SettingsTabRight;
        private readonly InputAction m_MenuMap_Escape;
        public struct MenuMapActions
        {
            private @PlayerInput m_Wrapper;
            public MenuMapActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @SettingsTabLeft => m_Wrapper.m_MenuMap_SettingsTabLeft;
            public InputAction @SettingsTabRight => m_Wrapper.m_MenuMap_SettingsTabRight;
            public InputAction @Escape => m_Wrapper.m_MenuMap_Escape;
            public InputActionMap Get() { return m_Wrapper.m_MenuMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MenuMapActions set) { return set.Get(); }
            public void SetCallbacks(IMenuMapActions instance)
            {
                if (m_Wrapper.m_MenuMapActionsCallbackInterface != null)
                {
                    @SettingsTabLeft.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSettingsTabLeft;
                    @SettingsTabLeft.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSettingsTabLeft;
                    @SettingsTabLeft.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSettingsTabLeft;
                    @SettingsTabRight.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSettingsTabRight;
                    @SettingsTabRight.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSettingsTabRight;
                    @SettingsTabRight.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnSettingsTabRight;
                    @Escape.started -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnEscape;
                    @Escape.performed -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnEscape;
                    @Escape.canceled -= m_Wrapper.m_MenuMapActionsCallbackInterface.OnEscape;
                }
                m_Wrapper.m_MenuMapActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @SettingsTabLeft.started += instance.OnSettingsTabLeft;
                    @SettingsTabLeft.performed += instance.OnSettingsTabLeft;
                    @SettingsTabLeft.canceled += instance.OnSettingsTabLeft;
                    @SettingsTabRight.started += instance.OnSettingsTabRight;
                    @SettingsTabRight.performed += instance.OnSettingsTabRight;
                    @SettingsTabRight.canceled += instance.OnSettingsTabRight;
                    @Escape.started += instance.OnEscape;
                    @Escape.performed += instance.OnEscape;
                    @Escape.canceled += instance.OnEscape;
                }
            }
        }
        public MenuMapActions @MenuMap => new MenuMapActions(this);

        // PlayerMap
        private readonly InputActionMap m_PlayerMap;
        private IPlayerMapActions m_PlayerMapActionsCallbackInterface;
        private readonly InputAction m_PlayerMap_Interact;
        private readonly InputAction m_PlayerMap_Move;
        private readonly InputAction m_PlayerMap_Look;
        private readonly InputAction m_PlayerMap_Run;
        private readonly InputAction m_PlayerMap_Crouch;
        public struct PlayerMapActions
        {
            private @PlayerInput m_Wrapper;
            public PlayerMapActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Interact => m_Wrapper.m_PlayerMap_Interact;
            public InputAction @Move => m_Wrapper.m_PlayerMap_Move;
            public InputAction @Look => m_Wrapper.m_PlayerMap_Look;
            public InputAction @Run => m_Wrapper.m_PlayerMap_Run;
            public InputAction @Crouch => m_Wrapper.m_PlayerMap_Crouch;
            public InputActionMap Get() { return m_Wrapper.m_PlayerMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerMapActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerMapActions instance)
            {
                if (m_Wrapper.m_PlayerMapActionsCallbackInterface != null)
                {
                    @Interact.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnInteract;
                    @Move.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnMove;
                    @Look.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnLook;
                    @Run.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnRun;
                    @Run.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnRun;
                    @Run.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnRun;
                    @Crouch.started -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnCrouch;
                    @Crouch.performed -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnCrouch;
                    @Crouch.canceled -= m_Wrapper.m_PlayerMapActionsCallbackInterface.OnCrouch;
                }
                m_Wrapper.m_PlayerMapActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @Run.started += instance.OnRun;
                    @Run.performed += instance.OnRun;
                    @Run.canceled += instance.OnRun;
                    @Crouch.started += instance.OnCrouch;
                    @Crouch.performed += instance.OnCrouch;
                    @Crouch.canceled += instance.OnCrouch;
                }
            }
        }
        public PlayerMapActions @PlayerMap => new PlayerMapActions(this);
        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        public interface IMenuMapActions
        {
            void OnSettingsTabLeft(InputAction.CallbackContext context);
            void OnSettingsTabRight(InputAction.CallbackContext context);
            void OnEscape(InputAction.CallbackContext context);
        }
        public interface IPlayerMapActions
        {
            void OnInteract(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnCrouch(InputAction.CallbackContext context);
        }
    }
}
